name: Push images to docker registry
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker images
        run: |
          docker build -t kevaron28/multi-react ./fibo-react
          docker build -t kevaron28/multi-server ./server
          docker build -t kevaron28/multi-worker ./worker
          docker build -t kevaron28/multi-nginx ./nginx
      - name: push docker images
        run: |
          docker push kevaron28/multi-nginx
          docker push kevaron28/multi-react
          docker push kevaron28/multi-server
          docker push kevaron28/multi-worker
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-657111133035
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
