name: Push images to docker registry
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker images
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/multi-react -f Dockerfile ./fibo-react
          docker build -t ${{secrets.DOCKER_USERNAME}}/multi-server -f Dockerfile ./server
          docker build -t ${{secrets.DOCKER_USERNAME}}/multi-worker -f Dockerfile ./worker
          docker build -t ${{secrets.DOCKER_USERNAME}}/multi-nginx -f Dockerfile ./nginx
      - name: push docker images
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/multi-react
          docker push ${{secrets.DOCKER_USERNAME}}R/multi-server
          docker push ${{secrets.DOCKER_USERNAME}}/multi-worker
          docker push ${{secrets.DOCKER_USERNAME}}/multi-nginx
