name: Push images to docker registry
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t kevaron28/multi-react:v1 -f Dockerfile ./fibo-react
      - name: push docker images
        run: |
          docker push kevaron28/multi-react:v1
